### ISSUE TITLE
Add maplibre package

### ISSUE THREAD

**Issue by crazycapivara** [posit-dev/shinylive#100]
It would be nice if you could add the [maplibre](https://github.com/eodaGmbH/py-maplibregl) package to the build.
I alread tried to use `micropip.install`, but there is some conflict.

**Comment by wch** [comment]
That is something that it outside of our control -- it would have to be loadable in Pyodide, but it doesn't seem to work when I run this in the latest version of Pyodide at https://pyodide.org/en/stable/console.html :

```
import micropip
await micropip.install("maplibre")
```
