### ISSUE TITLE
R examples all fail

### ISSUE THREAD

**Issue by bomeara** [posit-dev/shinylive#120]
```
> Error: there is no package called ‘renv’
Error: there is no package called ‘shiny’
```

at https://shinylive.io/r/examples/ and https://posit-dev.github.io/shinylive/r/examples/ . Fails on OS X both Safari and Chrome

**Comment by gadenbuie** [comment]
Hi @bomeara, thanks for the report. We're working to fix a small issue with the package repository used by shinylive. It should be back in working order in an hour or so.

**Comment by gadenbuie** [comment]
@bomeara this should be all cleared up now. You may need to clear your browser cache for shinylive.io to get the fix. (In Chrome, while viewing a [shinylive example](https://shinylive.io/r), under **View**, click **Clear cache and refresh**.)
