### ISSUE TITLE
Automatic R package download does not work with custom repositories

### ISSUE THREAD

**Issue by georgestagg** [posit-dev/shinylive#125]
See discussion in https://github.com/r-wasm/actions/issues/18 for details.

The issue is that at app startup `renv` searches for packages inside the Shinylive app. Then, we then download each of them from the default webR binary repository. However, we might not want to download all packages from the default repo -- we might want to load them from a personal repo built with r-wasm/actions, R Universe, or somewhere else entirely.

The relevant R code:
https://github.com/posit-dev/shinylive/blob/6afcdc86871073df46425317c0c182f89b83c3b0/src/hooks/useWebR.tsx#L256-L267

We should have some way to signal to Shinylive that we have a package from a custom repository we want to load. Some immediate options come to mind, in order of my personal preference.

1) Setup a new user library at startup so that `webr::install()` has priority over packages that are downloaded automatically.
2) Somehow allow for defining a custom repository list for the automatic package download system.
3) Document that automatic packages can be removed with `webr::unmount()` (P.S. Should we shim `remove.packages()` to do this in any case?)

---

Note: This issue should not affect Python apps. R apps deployed with `shinylive::export()` will be unaffected going forward, since in a future releases of r-shinylive the `shinylive::export()` function will gather the package references for packages installed on the local machine and deploy them directly with the app.

**Comment by eingemaischt** [comment]
I am running into the same issue:

I am using bioconductor packages that are for example in R Universe.

Using shinylive::export does neither download them from there nor does it offer a possibility to add a list of repositories.

Or is it possible via global/env variable to configure a list of repositories?

**Comment by georgestagg** [comment]
I think the best way to handle bioconductor is in the [Shinylive R package](https://github.com/posit-dev/r-shinylive). We should detect bioconductor packages and download the associated Wasm binary from R-Universe, even if the package has been installed from the official bioconductor repo.

I have made an issue to track that separately here: https://github.com/posit-dev/r-shinylive/issues/125

**Comment by georgestagg** [comment]
Now that https://github.com/posit-dev/r-shinylive/issues/125 has been merged, this should now work in the latest version of the R Shinylive package; not on CRAN yet, but a development version can be installed with `pak:pak("posit-dev/r-shinylive")`.

CRAN packages are downloaded from https://repo.r-wasm.org.
R-Universe and Bioconductor packages are downloaded from R-Universe.
Custom packages are downloaded from custom repository, or GitHub Release images, generated via [r-wasm/actions](https://github.com/r-wasm/actions).
