### ISSUE TITLE
Include `libsass-python` in pre-built pyodide packages

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/shinylive#160]
libsass cannot be installed currently, but it can be built for pyodide. We should bundle libsass with shinylive so that users don't need to figure out how to install it themselves. Including libsass will enable apps with dynamic theming -- using `shiny.ui.Theme()` from Shiny for Pyhton v1.0.0` -- in shinylive.

As part of the theme work and exploration, I confirmed that libsass will build for pyodide in a fork at https://github.com/gadenbuie/libsass-python.

With the current version of shinylive, users can add the following to `requirements.txt` to install libsass:

```
https://pkg.garrickadenbuie.com/libsass-python/libsass-0.23.0-cp312-abi3-pyodide_2024_0_wasm32.whl
```

Here's [an example app on shinylive with dynamic theming](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4mQiABM4dZfI4AdCPp1YoAczgB9YqjIsAFPqaOmNDgBtXUAEau4AXgAqdPJweA5OZGxw8L5G-pHwtgCUGFBqauYaNFDyrja2guJQdNi+umAAxACclQAsAGx1AKxliaEQifqGHBhcCmTmLK4cGnT2kGXKZQAKHIQA1kxQTBDyMJ6aE0wwXL4ADMowUHy+AIy7+0wAblCuwb6Nux0GEADuHBFMRoRFaraEHiJzKUwBQ+GQALSeEzggqHYotRBhRxvD5GDzYYiKAbDOCeIpJREQJzEpgotifbosHF40bDYFUjQ0zZWSjAjQsOZkKwIpEk4llAAycBoMgZuKKTBI5EoZDKnSJfKYAAFVCMMKDZQq+ZlWGQoBRzD4RQTeYqVHAyPI6ESaGU4nBWNSJRxRCAAOQsiBusQ0WR9DBimlJJhwVwsB1u-7EcNqN0AXwwcogYDjeHA0Hg1CEAEcdEJ4OQWOqwfgiKQKFRkGwyGRUCxEAB6BuoOYmDAmIp0WZzVKUTw6OAYEgwBtDTwsKAiGHYCKkUccceTljg3YYABMAGYMLtwYRUBuTmvwV4OBvp8Q1DjzGvdmuauZduYXpOYBu1xgXmxXCmALpAA).

**Comment by wch** [comment]
This is the first thing that comes to mind:

- Add a make target which downloads the file to the package/ directory, and update the `all` target to include it
- Add an entry for libsass-python in shinylive_requirements.json.

And then I think a `make all` should do it.

**Comment by gadenbuie** [comment]
Thanks @wch, that was the path I was headed down and it helped to have your confirmation. It worked out and #187 is ready for review.
