### ISSUE TITLE
Shinylive example not working

### ISSUE THREAD

**Issue by chaehni** [posit-dev/shinylive#181]
I'm getting started with shiny express and shiny live and found the "Restaurant tipping" example  on this page: https://shiny.posit.co/blog/posts/shiny-express/

Running it with a server works fine locally. I then wanted to convert it to a shinylive static webpage but failed with the error:
`ValueError: Can't find a pure Python 3 wheel for 'statsmodels!=0.14.2,>=0.12'.`

However, this example is also linked to shinylive.io from the page mentioned above and produces the same error message.
So I'm wondering if this Dashboard is supposed to work with shinylive and how it could be fixed. Unfortunately, I was not able to figure out what part of the code uses the statsmodel package.

**Comment by gadenbuie** [comment]
Thanks for letting us know! We're currently tracking this in https://github.com/posit-dev/py-shiny-site/issues/218. I'm going to close this to reduce duplicate tickets; please follow that issue for updates.

**Comment by chaehni** [comment]
Sorry for the duplicate. I must have missed that.
But I'm glad to hear, that this is being worked on.
