### ISSUE TITLE
v0.9.1 regression

### ISSUE THREAD

**Issue by vatula** [posit-dev/shinylive#190]
"future" whl is missing in the latest shinylive v0.9.1 whereas it is present in 0.9.0.
It also crashes my shinylive  with: ![Image](https://github.com/user-attachments/assets/6d60db2f-3ddb-4b7c-95fc-4e72eba48663)

**Comment by gadenbuie** [comment]
Hmmm, I think something else is going on here. `future` is definitely in the shinylive v0.9.1 assets (it's at `shinylive/pyodide/future-1.0.0-py3-none-any.whl` in the shinylive tarball attached to [the v0.9.1 release](https://github.com/posit-dev/shinylive/releases/tag/v0.9.1)). The apps on https://shinylive.io/py/examples all appear to be working as well and I can import `future` there without issues.

Can you share a minimal example that reproduces the issue?

**Comment by vatula** [comment]
Sorry, false alarm. The version upgrade coincided with some of the changes locally. import future was removed as unused from shinyapp. This caused shiny exporter to miss the package
