### ISSUE TITLE
run-python-blocks.ts doesn't recognize code blocks in Reveal.js

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/shinylive#60]
Here's what code blocks look like in `format: html`:
```html
<pre class="shinylive-r" data-engine="r"><code>#| standalone: true
```

Here's what code blocks look like in `format: revealjs':
```html
<div class="sourceCode" id="cb1" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a href="#cb1-1"></a>#| standalone: true</span>
```

Relevant code: https://github.com/posit-dev/shinylive/blob/ff9d728298e1bf570418267fe1d91cc1b58dfc2e/src/run-python-blocks.ts#L13C1-L20

**Comment by wch** [comment]
I just tested, and it appears to work for Shinylive Python apps:

<img width="1067" alt="image" src="https://github.com/posit-dev/shinylive/assets/86978/8cf80c00-eeff-48d2-b614-d9ccaccb3abd">

	---
	title: "Shinylive RevealJS"
	format: revealjs
	filters:
	  - shinylive
	---
	
	## Shinylive
	
	```{shinylive-python}
	#| standalone: true
	#| viewerHeight: 420
	from shiny import App, render, ui
	
	app_ui = ui.page_fluid(
	    ui.h2("Hello Shiny!"),
	    ui.input_slider("n", "N", 0, 100, 20),
	    ui.output_text_verbatim("txt"),
	)
	
	
	def server(input, output, session):
	    @output
	    @render.text
	    def txt():
	        return f"n*2 is {input.n() * 2}"
	
	
	app = App(app_ui, server)
	```

**Comment by wch** [comment]
It is broken for R, though:

<img width="897" alt="image" src="https://github.com/posit-dev/shinylive/assets/86978/3d5b0ac8-b8d8-4e22-ba85-3b91c44e71ae">


	---
	title: "Shinylive RevealJS"
	format: revealjs
	filters:
	  - shinylive
	---
	
	## Shinylive R
	
	```{shinylive-r}
	#| standalone: true
	#| viewerHeight: 420
	ui <- fluidPage(
	  sliderInput("obs", "Number of observations:",
	    min = 0, max = 1000, value = 500
	  ),
	  plotOutput("distPlot")
	)
	
	server <- function(input, output) {
	  output$distPlot <- renderPlot({
	    hist(rnorm(input$obs))
	  })
	}
	
	shinyApp(ui, server)
	```
